#!/bin/bash

quiet=${1-''}

pkg_name=$(basename $PWD)
url=https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=${pkg_name}

current_ver=$(source PKGBUILD && echo $pkgver)

tmp_file=$(mktemp)
latest_ver=$(curl -sf $url -o $tmp_file && source $tmp_file && echo $pkgver)
rm $tmp_file

if [[ "$current_ver" == "$latest_ver" ]]
then
  if [[ "$quiet" != "-q" ]]
  then
    echo "up-to-date: $current_ver"
  fi
  exit 0
else
  if [[ "$quiet" != "-q" ]]
  then
    echo "Out of date"
    echo "Current: $current_ver"
    echo "Latest: $latest_ver"
  fi
  exit 1
fi
  
  
